### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by vilhalmer** [Zylann/godot_debug_draw#13]
This is a great tool that I'd love to use in an upcoming project, but I need to know if I legally can. :) Would it be possible to add a LICENSE file of your choosing?

**Comment by Zylann** [comment]
It is here https://github.com/Zylann/godot_debug_draw/blob/master/addons/zylann.debug_draw/LICENSE.md

The Github interface doesn't pick it up in the main page because it's inside the addon. If I put it at the root, it would however not be picked up when you install the addon in your project. The repro is structured that way (like many other addons) because when giving the address to the asset library, downloading the addon matches the expected hierarchy.

**Comment by vilhalmer** [comment]
Ah, my bad! Thanks for the pointer.
